name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node.js 
      
        uses: actions/setup-node@v2
        with: 
          node-version: '16'
          
      # - name: 'Create env file'
     #    run: |
      #     touch .env
      #     echo JET_ENDPOINT="${{ secrets.JET_ENDPOINT }}" >> .env
     #      echo JET_USERNAME="${{ secrets.JET_USERNAME }}" >> .env
     #      echo JET_PASSWORD="${{ secrets.JET_PASSWORD }}" >> .env
    #       echo JET_INTEGRATION_KEY="${{ secrets.JET_INTEGRATION_KEY }}" >> .env
    #       echo JET_STORE_ID="${{ secrets.JET_STORE_ID }}" >> .env
     #      echo EMBLUE_TOKEN="${{ secrets.EMBLUE_TOKEN }}" >> .env
      #     echo EMBLUE_USERNAME="${{ secrets.EMBLUE_USERNAME }}" >> .env    
     #      echo EMBLUE_PASSWORD="${{ secrets.EMBLUE_PASSWORD }}" >> .env
     #      echo EMBLUE_ENDPOINT="${{ secrets.EMBLUE_ENDPOINT }}" >> .env
     #      echo EMBLUE_TRACKENDPOINT="${{ secrets.EMBLUE_TRACKENDPOINT }}" >> .env
      #     echo TIMEOUT_API="${{ secrets.TIMEOUT_API }}" >> .env       
      #     echo TRACK_AUTH_TOKEN="${{ secrets.TRACK_AUTH_TOKEN }}" >> .env      
       #    echo EMBLUE_EVENT_NAME="${{ secrets.EMBLUE_EVENT_NAME }}" >> .env                                 
       #    cat .env
      - run: npm i

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/up2you/
          remote_host: ec2-3-86-212-88.compute-1.amazonaws.com
          remote_user: ec2-user
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
